category:
  type: list
  list_type: category
  default: ""
  description: "Выберите категорию"
max_list_length:
  type: integer
  default: 5
  min: 1
  max: 5
  description: "Сколько показывать в списке топиков?"
plugin_outlet:
  type: enum
  default: "above-main-container"
  choices:
    - "above-main-container"
    - "below-site-header"
  description: "Advanced setting for additional customization"
