feed_category:
  type: list
  list_type: category
  default: ""
  description: "Выберите категорию"
max_list_length:
  type: integer
  default: 5
  min: 1
  max: 5
  description: "Сколько показывать в списке топиков?"
